{% set name = "napari-blender-bridge" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-blender-bridge-{{ version }}.tar.gz
  sha256: 972905ed5f8fe24cd3fcb021c6422aa4e1409099b64d6369593212d89a144bdf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - napari-plugin-engine >=0.1.4
    - napari-process-points-and-surfaces >=0.4.2
    - napari-tools-menu
    - numpy
    - python >=3.8
    - vedo

test:
  imports:
    - napari_blender_bridge
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-blender-bridge
  summary: Transfer surface layers between Napari and Blender
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
